# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ywxrGn_QkldBRecBWzuo07MVWeAtMMF
"""

import streamlit as st
import numpy as np
import pickle

# Load model & scaler
with open("fraud_model.pkl", "rb") as f:
    model = pickle.load(f)

with open("scaler.pkl", "rb") as f:
    scaler = pickle.load(f)

st.title(" Fraud Detection Demo")

# Simplified inputs
amount = st.number_input("Transaction Amount", value=100.0)
hour = st.slider("Transaction Hour (0-23)", 0, 23, 12)
tx_type = st.selectbox("Transaction Type", ["Online", "POS"])
tx_type_num = 0 if tx_type=="Online" else 1

# Create input array
input_array = np.array([amount, hour, tx_type_num]).reshape(1, -1)
input_array[:,0] = scaler.transform(input_array[:,0].reshape(-1,1))  # scale amount

if st.button("Predict Fraud"):
    prediction = model.predict(input_array)
    if prediction[0] == 1:
        st.error(" Fraudulent Transaction Detected!")
    else:
        st.success("Transaction is Normal")
