# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ywxrGn_QkldBRecBWzuo07MVWeAtMMF
"""
import streamlit as st
import numpy as np
import pickle

# Load trained model and scaler
with open("fraud_model.pkl", "rb") as f:
    model = pickle.load(f)
with open("scaler.pkl", "rb") as f:
    scaler = pickle.load(f)

st.title("Credit Card Fraud Detection")

# V1 to V28 + Amount
# Normal transaction (model will predict 0)
normal_transaction = [
    -1.359807, -0.072781, 2.536347, 1.378155, -0.338321, 0.462388,
    0.239599, 0.098698, 0.363787, 0.090794, -0.551600, -0.617800,
    -0.991390, -0.311169, 1.468177, -0.470401, 0.207971, 0.025791,
    0.403993, 0.251412, -0.018307, 0.277838, -0.110474, 0.066928,
    0.128539, -0.189115, 0.133558, 149.62  # Amount
]

# Fraudulent transaction (model will predict 1)
fraud_transaction = [
    1.191857, 0.266151, 0.166480, 0.448154, 0.060018, -0.082360,
    -0.078802, 0.085101, -0.255425, -0.166974, 1.612727, 1.065235,
    0.489095, -0.143772, 0.635558, 0.463917, -0.114804, -0.183361,
    -0.145783, -0.069083, -0.225775, -0.638671, 0.101288, -0.339846,
    0.167170, 0.125895, -0.008983, 378.66  # Amount
]

# select
transaction_type = st.selectbox("Select Transaction:", ["Normal Transaction", "Fraudulent Transaction"])

if transaction_type == "Normal Transaction":
    input_array = np.array(normal_transaction).reshape(1, -1)
else:
    input_array = np.array(fraud_transaction).reshape(1, -1)

# Scale Amount
input_array[0, -1] = scaler.transform(np.array([[input_array[0, -1]]]))[0][0]

# Ensure float
input_array = input_array.astype(float)

# Predict
if st.button("Predict Fraud"):
    prediction = model.predict(input_array)
    prob = model.predict_proba(input_array)[:,1][0]

    if prediction[0] == 1:
        st.error(f"Fraudulent Transaction Detected! Probability: {prob:.2f}")
    else:
        st.success(f"Transaction is Normal. Probability of Fraud: {prob:.2f}")
